// Code generated by generate.go: DO NOT EDIT.

package glm

// Mat3f is an alias for the float32 variant of Mat3
type Mat3f = Mat3[float32]

// Mat3u is an alias for the uint32 variant of Mat3
type Mat3u = Mat3[uint32]

// Mat3uh is an alias for the uint16 variant of Mat3
type Mat3uh = Mat3[uint16]

// Mat3 is a 3x3 matrix.
// The default value is the identity matrix.
type Mat3[T Numeric] struct {
	values [3][3]T
}

func Mat3Of[T Numeric](values [3][3]T) Mat3[T] {
	return Mat3[T]{
		values: [3][3]T{
			{
				values[0][0] - 1,
				values[0][1],
				values[0][2],
			},
			{
				values[1][0],
				values[1][1] - 1,
				values[1][2],
			},
			{
				values[2][0],
				values[2][1],
				values[2][2] - 1,
			},
		},
	}
}

func IdentityMat3[T Numeric]() Mat3[T] {
	return Mat3[T]{}
}

func (m Mat3[T]) Mul(o Mat3[T]) Mat3[T] {
	mv := &m.values
	ov := &o.values

	return Mat3[T]{
		values: [3][3]T{
			{
				(mv[0][0]+1)*(ov[0][0]+1) + (mv[1][0]+0)*(ov[0][1]+0) + (mv[2][0]+0)*(ov[0][2]+0) - 1,
				(mv[0][1]+0)*(ov[0][0]+1) + (mv[1][1]+1)*(ov[0][1]+0) + (mv[2][1]+0)*(ov[0][2]+0),
				(mv[0][2]+0)*(ov[0][0]+1) + (mv[1][2]+0)*(ov[0][1]+0) + (mv[2][2]+1)*(ov[0][2]+0),
			},
			{
				(mv[0][0]+1)*(ov[1][0]+0) + (mv[1][0]+0)*(ov[1][1]+1) + (mv[2][0]+0)*(ov[1][2]+0),
				(mv[0][1]+0)*(ov[1][0]+0) + (mv[1][1]+1)*(ov[1][1]+1) + (mv[2][1]+0)*(ov[1][2]+0) - 1,
				(mv[0][2]+0)*(ov[1][0]+0) + (mv[1][2]+0)*(ov[1][1]+1) + (mv[2][2]+1)*(ov[1][2]+0),
			},
			{
				(mv[0][0]+1)*(ov[2][0]+0) + (mv[1][0]+0)*(ov[2][1]+0) + (mv[2][0]+0)*(ov[2][2]+1),
				(mv[0][1]+0)*(ov[2][0]+0) + (mv[1][1]+1)*(ov[2][1]+0) + (mv[2][1]+0)*(ov[2][2]+1),
				(mv[0][2]+0)*(ov[2][0]+0) + (mv[1][2]+0)*(ov[2][1]+0) + (mv[2][2]+1)*(ov[2][2]+1) - 1,
			},
		},
	}
}

func (m Mat3[T]) Transpose() Mat3[T] {
	mv := &m.values

	return Mat3[T]{
		values: [3][3]T{
			{
				mv[0][0],
				mv[1][0],
				mv[2][0],
			},
			{
				mv[0][1],
				mv[1][1],
				mv[2][1],
			},
			{
				mv[0][2],
				mv[1][2],
				mv[2][2],
			},
		},
	}
}

func (m Mat3[T]) Values() [3][3]T {
	values := m.values
	values[0][0] += 1
	values[1][1] += 1
	values[2][2] += 1
	return values
}

func (m Mat3[T]) m00() T {
	return (m.values[0][0] + 1)
}

func (m Mat3[T]) m01() T {
	return (m.values[0][1] + 0)
}

func (m Mat3[T]) m02() T {
	return (m.values[0][2] + 0)
}

func (m Mat3[T]) m10() T {
	return (m.values[1][0] + 0)
}

func (m Mat3[T]) m11() T {
	return (m.values[1][1] + 1)
}

func (m Mat3[T]) m12() T {
	return (m.values[1][2] + 0)
}

func (m Mat3[T]) m20() T {
	return (m.values[2][0] + 0)
}

func (m Mat3[T]) m21() T {
	return (m.values[2][1] + 0)
}

func (m Mat3[T]) m22() T {
	return (m.values[2][2] + 1)
}
