// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec2f is an alias for the float32 variant of Vec2
type Vec2f = Vec2[float32]

// Vec2u is an alias for the uint32 variant of Vec2
type Vec2u = Vec2[uint32]

// Vec2uh is an alias for the uint16 variant of Vec2
type Vec2uh = Vec2[uint16]

// Vec2 is a vector of dimension 2.
type Vec2[T Numeric] [2]T

func (lhs Vec2[T]) Dot(rhs Vec2[T]) T {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1]
}

func (lhs Vec2[T]) LengthSqr() T {
	return lhs.Dot(lhs)
}

func (lhs Vec2[T]) Length() T {
	return T(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec2[T]) Normalize() Vec2[T] {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec2[T]) Scale(s T) Vec2[T] {
	return Vec2[T]{
		lhs[0] * s,
		lhs[1] * s,
	}
}

func (lhs Vec2[T]) Reciprocal() Vec2[T] {
	return Vec2[T]{
		1.0 / lhs[0],
		1.0 / lhs[1],
	}
}

func (lhs Vec2[T]) Add(rhs Vec2[T]) Vec2[T] {
	return Vec2[T]{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
	}
}

func (lhs Vec2[T]) Sub(rhs Vec2[T]) Vec2[T] {
	return Vec2[T]{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
	}
}

func (lhs Vec2[T]) Mul(rhs Vec2[T]) Vec2[T] {
	return Vec2[T]{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
	}
}

func (lhs Vec2[T]) Div(rhs Vec2[T]) Vec2[T] {
	return Vec2[T]{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
	}
}

func (lhs Vec2[T]) Min(rhs Vec2[T]) Vec2[T] {
	return Vec2[T]{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
	}
}

func (lhs Vec2[T]) Max(rhs Vec2[T]) Vec2[T] {
	return Vec2[T]{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
	}
}

func (lhs Vec2[T]) Extend(z T) Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		z,
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec2[T]) SwizzleXX() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec2[T]) SwizzleXY() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[1],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec2[T]) SwizzleYX() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec2[T]) SwizzleYY() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[1],
	}
}

func (lhs Vec2[T]) XY() (x, y T) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec2[T]) ToVec2f() Vec2f {
	return Vec2f{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2[T]) ToWGPU() [2]float32 {
	return [2]float32{
		float32(lhs[0]),
		float32(lhs[1]),
	}
}

func (lhs Vec2[T]) String() string {
	return fmt.Sprintf(
		"vec2(%v, %v)",
		lhs[0],
		lhs[1],
	)
}
