// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec4f is an alias for the float32 variant of Vec4
type Vec4f = Vec4[float32]

// Vec4u is an alias for the uint32 variant of Vec4
type Vec4u = Vec4[uint32]

// Vec4uh is an alias for the uint16 variant of Vec4
type Vec4uh = Vec4[uint16]

// Vec4 is a vector of dimension 4.
type Vec4[T Numeric] [4]T

func (lhs Vec4[T]) Dot(rhs Vec4[T]) T {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2] + lhs[3]*rhs[3]
}

func (lhs Vec4[T]) LengthSqr() T {
	return lhs.Dot(lhs)
}

func (lhs Vec4[T]) Length() T {
	return T(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec4[T]) Normalize() Vec4[T] {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec4[T]) Scale(s T) Vec4[T] {
	return Vec4[T]{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
		lhs[3] * s,
	}
}

func (lhs Vec4[T]) Reciprocal() Vec4[T] {
	return Vec4[T]{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
		1.0 / lhs[3],
	}
}

func (lhs Vec4[T]) Add(rhs Vec4[T]) Vec4[T] {
	return Vec4[T]{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
		lhs[3] + rhs[3],
	}
}

func (lhs Vec4[T]) Sub(rhs Vec4[T]) Vec4[T] {
	return Vec4[T]{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
		lhs[3] - rhs[3],
	}
}

func (lhs Vec4[T]) Mul(rhs Vec4[T]) Vec4[T] {
	return Vec4[T]{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
		lhs[3] * rhs[3],
	}
}

func (lhs Vec4[T]) Div(rhs Vec4[T]) Vec4[T] {
	return Vec4[T]{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
		lhs[3] / rhs[3],
	}
}

func (lhs Vec4[T]) Min(rhs Vec4[T]) Vec4[T] {
	return Vec4[T]{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
		min(lhs[3], rhs[3]),
	}
}

func (lhs Vec4[T]) Max(rhs Vec4[T]) Vec4[T] {
	return Vec4[T]{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
		max(lhs[3], rhs[3]),
	}
}

func (lhs Vec4[T]) Truncate() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec4[T]) SwizzleXX() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec4[T]) SwizzleXY() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec4[T]) SwizzleXZ() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[2],
	}
}

// SwizzleXW returns a new vector with the components of this
// vector in the order of XW.
func (lhs Vec4[T]) SwizzleXW() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[3],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec4[T]) SwizzleYX() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec4[T]) SwizzleYY() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec4[T]) SwizzleYZ() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[2],
	}
}

// SwizzleYW returns a new vector with the components of this
// vector in the order of YW.
func (lhs Vec4[T]) SwizzleYW() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[3],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec4[T]) SwizzleZX() Vec2[T] {
	return Vec2[T]{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec4[T]) SwizzleZY() Vec2[T] {
	return Vec2[T]{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec4[T]) SwizzleZZ() Vec2[T] {
	return Vec2[T]{
		lhs[2],
		lhs[2],
	}
}

// SwizzleZW returns a new vector with the components of this
// vector in the order of ZW.
func (lhs Vec4[T]) SwizzleZW() Vec2[T] {
	return Vec2[T]{
		lhs[2],
		lhs[3],
	}
}

// SwizzleWX returns a new vector with the components of this
// vector in the order of WX.
func (lhs Vec4[T]) SwizzleWX() Vec2[T] {
	return Vec2[T]{
		lhs[3],
		lhs[0],
	}
}

// SwizzleWY returns a new vector with the components of this
// vector in the order of WY.
func (lhs Vec4[T]) SwizzleWY() Vec2[T] {
	return Vec2[T]{
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZ returns a new vector with the components of this
// vector in the order of WZ.
func (lhs Vec4[T]) SwizzleWZ() Vec2[T] {
	return Vec2[T]{
		lhs[3],
		lhs[2],
	}
}

// SwizzleWW returns a new vector with the components of this
// vector in the order of WW.
func (lhs Vec4[T]) SwizzleWW() Vec2[T] {
	return Vec2[T]{
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec4[T]) SwizzleXXX() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec4[T]) SwizzleXXY() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec4[T]) SwizzleXXZ() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXW returns a new vector with the components of this
// vector in the order of XXW.
func (lhs Vec4[T]) SwizzleXXW() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec4[T]) SwizzleXYX() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec4[T]) SwizzleXYY() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec4[T]) SwizzleXYZ() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYW returns a new vector with the components of this
// vector in the order of XYW.
func (lhs Vec4[T]) SwizzleXYW() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec4[T]) SwizzleXZX() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec4[T]) SwizzleXZY() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec4[T]) SwizzleXZZ() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZW returns a new vector with the components of this
// vector in the order of XZW.
func (lhs Vec4[T]) SwizzleXZW() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWX returns a new vector with the components of this
// vector in the order of XWX.
func (lhs Vec4[T]) SwizzleXWX() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWY returns a new vector with the components of this
// vector in the order of XWY.
func (lhs Vec4[T]) SwizzleXWY() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWZ returns a new vector with the components of this
// vector in the order of XWZ.
func (lhs Vec4[T]) SwizzleXWZ() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWW returns a new vector with the components of this
// vector in the order of XWW.
func (lhs Vec4[T]) SwizzleXWW() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec4[T]) SwizzleYXX() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec4[T]) SwizzleYXY() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec4[T]) SwizzleYXZ() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXW returns a new vector with the components of this
// vector in the order of YXW.
func (lhs Vec4[T]) SwizzleYXW() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec4[T]) SwizzleYYX() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec4[T]) SwizzleYYY() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec4[T]) SwizzleYYZ() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYW returns a new vector with the components of this
// vector in the order of YYW.
func (lhs Vec4[T]) SwizzleYYW() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec4[T]) SwizzleYZX() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec4[T]) SwizzleYZY() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec4[T]) SwizzleYZZ() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZW returns a new vector with the components of this
// vector in the order of YZW.
func (lhs Vec4[T]) SwizzleYZW() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWX returns a new vector with the components of this
// vector in the order of YWX.
func (lhs Vec4[T]) SwizzleYWX() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWY returns a new vector with the components of this
// vector in the order of YWY.
func (lhs Vec4[T]) SwizzleYWY() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWZ returns a new vector with the components of this
// vector in the order of YWZ.
func (lhs Vec4[T]) SwizzleYWZ() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWW returns a new vector with the components of this
// vector in the order of YWW.
func (lhs Vec4[T]) SwizzleYWW() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec4[T]) SwizzleZXX() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec4[T]) SwizzleZXY() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec4[T]) SwizzleZXZ() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXW returns a new vector with the components of this
// vector in the order of ZXW.
func (lhs Vec4[T]) SwizzleZXW() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec4[T]) SwizzleZYX() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec4[T]) SwizzleZYY() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec4[T]) SwizzleZYZ() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYW returns a new vector with the components of this
// vector in the order of ZYW.
func (lhs Vec4[T]) SwizzleZYW() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec4[T]) SwizzleZZX() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec4[T]) SwizzleZZY() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec4[T]) SwizzleZZZ() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZW returns a new vector with the components of this
// vector in the order of ZZW.
func (lhs Vec4[T]) SwizzleZZW() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWX returns a new vector with the components of this
// vector in the order of ZWX.
func (lhs Vec4[T]) SwizzleZWX() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWY returns a new vector with the components of this
// vector in the order of ZWY.
func (lhs Vec4[T]) SwizzleZWY() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWZ returns a new vector with the components of this
// vector in the order of ZWZ.
func (lhs Vec4[T]) SwizzleZWZ() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWW returns a new vector with the components of this
// vector in the order of ZWW.
func (lhs Vec4[T]) SwizzleZWW() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXX returns a new vector with the components of this
// vector in the order of WXX.
func (lhs Vec4[T]) SwizzleWXX() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXY returns a new vector with the components of this
// vector in the order of WXY.
func (lhs Vec4[T]) SwizzleWXY() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXZ returns a new vector with the components of this
// vector in the order of WXZ.
func (lhs Vec4[T]) SwizzleWXZ() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXW returns a new vector with the components of this
// vector in the order of WXW.
func (lhs Vec4[T]) SwizzleWXW() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYX returns a new vector with the components of this
// vector in the order of WYX.
func (lhs Vec4[T]) SwizzleWYX() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYY returns a new vector with the components of this
// vector in the order of WYY.
func (lhs Vec4[T]) SwizzleWYY() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYZ returns a new vector with the components of this
// vector in the order of WYZ.
func (lhs Vec4[T]) SwizzleWYZ() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYW returns a new vector with the components of this
// vector in the order of WYW.
func (lhs Vec4[T]) SwizzleWYW() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZX returns a new vector with the components of this
// vector in the order of WZX.
func (lhs Vec4[T]) SwizzleWZX() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZY returns a new vector with the components of this
// vector in the order of WZY.
func (lhs Vec4[T]) SwizzleWZY() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZ returns a new vector with the components of this
// vector in the order of WZZ.
func (lhs Vec4[T]) SwizzleWZZ() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZW returns a new vector with the components of this
// vector in the order of WZW.
func (lhs Vec4[T]) SwizzleWZW() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWX returns a new vector with the components of this
// vector in the order of WWX.
func (lhs Vec4[T]) SwizzleWWX() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWY returns a new vector with the components of this
// vector in the order of WWY.
func (lhs Vec4[T]) SwizzleWWY() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWZ returns a new vector with the components of this
// vector in the order of WWZ.
func (lhs Vec4[T]) SwizzleWWZ() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWW returns a new vector with the components of this
// vector in the order of WWW.
func (lhs Vec4[T]) SwizzleWWW() Vec3[T] {
	return Vec3[T]{
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXXXX returns a new vector with the components of this
// vector in the order of XXXX.
func (lhs Vec4[T]) SwizzleXXXX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXXY returns a new vector with the components of this
// vector in the order of XXXY.
func (lhs Vec4[T]) SwizzleXXXY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXXZ returns a new vector with the components of this
// vector in the order of XXXZ.
func (lhs Vec4[T]) SwizzleXXXZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXXXW returns a new vector with the components of this
// vector in the order of XXXW.
func (lhs Vec4[T]) SwizzleXXXW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXXYX returns a new vector with the components of this
// vector in the order of XXYX.
func (lhs Vec4[T]) SwizzleXXYX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXXYY returns a new vector with the components of this
// vector in the order of XXYY.
func (lhs Vec4[T]) SwizzleXXYY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXXYZ returns a new vector with the components of this
// vector in the order of XXYZ.
func (lhs Vec4[T]) SwizzleXXYZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXXYW returns a new vector with the components of this
// vector in the order of XXYW.
func (lhs Vec4[T]) SwizzleXXYW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXXZX returns a new vector with the components of this
// vector in the order of XXZX.
func (lhs Vec4[T]) SwizzleXXZX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXXZY returns a new vector with the components of this
// vector in the order of XXZY.
func (lhs Vec4[T]) SwizzleXXZY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXXZZ returns a new vector with the components of this
// vector in the order of XXZZ.
func (lhs Vec4[T]) SwizzleXXZZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXZW returns a new vector with the components of this
// vector in the order of XXZW.
func (lhs Vec4[T]) SwizzleXXZW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXXWX returns a new vector with the components of this
// vector in the order of XXWX.
func (lhs Vec4[T]) SwizzleXXWX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXXWY returns a new vector with the components of this
// vector in the order of XXWY.
func (lhs Vec4[T]) SwizzleXXWY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXXWZ returns a new vector with the components of this
// vector in the order of XXWZ.
func (lhs Vec4[T]) SwizzleXXWZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXXWW returns a new vector with the components of this
// vector in the order of XXWW.
func (lhs Vec4[T]) SwizzleXXWW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXYXX returns a new vector with the components of this
// vector in the order of XYXX.
func (lhs Vec4[T]) SwizzleXYXX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXYXY returns a new vector with the components of this
// vector in the order of XYXY.
func (lhs Vec4[T]) SwizzleXYXY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXYXZ returns a new vector with the components of this
// vector in the order of XYXZ.
func (lhs Vec4[T]) SwizzleXYXZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYXW returns a new vector with the components of this
// vector in the order of XYXW.
func (lhs Vec4[T]) SwizzleXYXW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXYYX returns a new vector with the components of this
// vector in the order of XYYX.
func (lhs Vec4[T]) SwizzleXYYX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYYY returns a new vector with the components of this
// vector in the order of XYYY.
func (lhs Vec4[T]) SwizzleXYYY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYYZ returns a new vector with the components of this
// vector in the order of XYYZ.
func (lhs Vec4[T]) SwizzleXYYZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXYYW returns a new vector with the components of this
// vector in the order of XYYW.
func (lhs Vec4[T]) SwizzleXYYW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXYZX returns a new vector with the components of this
// vector in the order of XYZX.
func (lhs Vec4[T]) SwizzleXYZX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXYZY returns a new vector with the components of this
// vector in the order of XYZY.
func (lhs Vec4[T]) SwizzleXYZY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXYZZ returns a new vector with the components of this
// vector in the order of XYZZ.
func (lhs Vec4[T]) SwizzleXYZZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXYZW returns a new vector with the components of this
// vector in the order of XYZW.
func (lhs Vec4[T]) SwizzleXYZW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXYWX returns a new vector with the components of this
// vector in the order of XYWX.
func (lhs Vec4[T]) SwizzleXYWX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXYWY returns a new vector with the components of this
// vector in the order of XYWY.
func (lhs Vec4[T]) SwizzleXYWY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXYWZ returns a new vector with the components of this
// vector in the order of XYWZ.
func (lhs Vec4[T]) SwizzleXYWZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXYWW returns a new vector with the components of this
// vector in the order of XYWW.
func (lhs Vec4[T]) SwizzleXYWW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXZXX returns a new vector with the components of this
// vector in the order of XZXX.
func (lhs Vec4[T]) SwizzleXZXX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXZXY returns a new vector with the components of this
// vector in the order of XZXY.
func (lhs Vec4[T]) SwizzleXZXY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZXZ returns a new vector with the components of this
// vector in the order of XZXZ.
func (lhs Vec4[T]) SwizzleXZXZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXZXW returns a new vector with the components of this
// vector in the order of XZXW.
func (lhs Vec4[T]) SwizzleXZXW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXZYX returns a new vector with the components of this
// vector in the order of XZYX.
func (lhs Vec4[T]) SwizzleXZYX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXZYY returns a new vector with the components of this
// vector in the order of XZYY.
func (lhs Vec4[T]) SwizzleXZYY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXZYZ returns a new vector with the components of this
// vector in the order of XZYZ.
func (lhs Vec4[T]) SwizzleXZYZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZYW returns a new vector with the components of this
// vector in the order of XZYW.
func (lhs Vec4[T]) SwizzleXZYW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXZZX returns a new vector with the components of this
// vector in the order of XZZX.
func (lhs Vec4[T]) SwizzleXZZX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZZY returns a new vector with the components of this
// vector in the order of XZZY.
func (lhs Vec4[T]) SwizzleXZZY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZZ returns a new vector with the components of this
// vector in the order of XZZZ.
func (lhs Vec4[T]) SwizzleXZZZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXZZW returns a new vector with the components of this
// vector in the order of XZZW.
func (lhs Vec4[T]) SwizzleXZZW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXZWX returns a new vector with the components of this
// vector in the order of XZWX.
func (lhs Vec4[T]) SwizzleXZWX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXZWY returns a new vector with the components of this
// vector in the order of XZWY.
func (lhs Vec4[T]) SwizzleXZWY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXZWZ returns a new vector with the components of this
// vector in the order of XZWZ.
func (lhs Vec4[T]) SwizzleXZWZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXZWW returns a new vector with the components of this
// vector in the order of XZWW.
func (lhs Vec4[T]) SwizzleXZWW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleXWXX returns a new vector with the components of this
// vector in the order of XWXX.
func (lhs Vec4[T]) SwizzleXWXX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXWXY returns a new vector with the components of this
// vector in the order of XWXY.
func (lhs Vec4[T]) SwizzleXWXY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXWXZ returns a new vector with the components of this
// vector in the order of XWXZ.
func (lhs Vec4[T]) SwizzleXWXZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXWXW returns a new vector with the components of this
// vector in the order of XWXW.
func (lhs Vec4[T]) SwizzleXWXW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleXWYX returns a new vector with the components of this
// vector in the order of XWYX.
func (lhs Vec4[T]) SwizzleXWYX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXWYY returns a new vector with the components of this
// vector in the order of XWYY.
func (lhs Vec4[T]) SwizzleXWYY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXWYZ returns a new vector with the components of this
// vector in the order of XWYZ.
func (lhs Vec4[T]) SwizzleXWYZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXWYW returns a new vector with the components of this
// vector in the order of XWYW.
func (lhs Vec4[T]) SwizzleXWYW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleXWZX returns a new vector with the components of this
// vector in the order of XWZX.
func (lhs Vec4[T]) SwizzleXWZX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXWZY returns a new vector with the components of this
// vector in the order of XWZY.
func (lhs Vec4[T]) SwizzleXWZY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXWZZ returns a new vector with the components of this
// vector in the order of XWZZ.
func (lhs Vec4[T]) SwizzleXWZZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleXWZW returns a new vector with the components of this
// vector in the order of XWZW.
func (lhs Vec4[T]) SwizzleXWZW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleXWWX returns a new vector with the components of this
// vector in the order of XWWX.
func (lhs Vec4[T]) SwizzleXWWX() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleXWWY returns a new vector with the components of this
// vector in the order of XWWY.
func (lhs Vec4[T]) SwizzleXWWY() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleXWWZ returns a new vector with the components of this
// vector in the order of XWWZ.
func (lhs Vec4[T]) SwizzleXWWZ() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleXWWW returns a new vector with the components of this
// vector in the order of XWWW.
func (lhs Vec4[T]) SwizzleXWWW() Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYXXX returns a new vector with the components of this
// vector in the order of YXXX.
func (lhs Vec4[T]) SwizzleYXXX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXXY returns a new vector with the components of this
// vector in the order of YXXY.
func (lhs Vec4[T]) SwizzleYXXY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXXZ returns a new vector with the components of this
// vector in the order of YXXZ.
func (lhs Vec4[T]) SwizzleYXXZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYXXW returns a new vector with the components of this
// vector in the order of YXXW.
func (lhs Vec4[T]) SwizzleYXXW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYXYX returns a new vector with the components of this
// vector in the order of YXYX.
func (lhs Vec4[T]) SwizzleYXYX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYXYY returns a new vector with the components of this
// vector in the order of YXYY.
func (lhs Vec4[T]) SwizzleYXYY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYXYZ returns a new vector with the components of this
// vector in the order of YXYZ.
func (lhs Vec4[T]) SwizzleYXYZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYXYW returns a new vector with the components of this
// vector in the order of YXYW.
func (lhs Vec4[T]) SwizzleYXYW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYXZX returns a new vector with the components of this
// vector in the order of YXZX.
func (lhs Vec4[T]) SwizzleYXZX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYXZY returns a new vector with the components of this
// vector in the order of YXZY.
func (lhs Vec4[T]) SwizzleYXZY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYXZZ returns a new vector with the components of this
// vector in the order of YXZZ.
func (lhs Vec4[T]) SwizzleYXZZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXZW returns a new vector with the components of this
// vector in the order of YXZW.
func (lhs Vec4[T]) SwizzleYXZW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYXWX returns a new vector with the components of this
// vector in the order of YXWX.
func (lhs Vec4[T]) SwizzleYXWX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYXWY returns a new vector with the components of this
// vector in the order of YXWY.
func (lhs Vec4[T]) SwizzleYXWY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYXWZ returns a new vector with the components of this
// vector in the order of YXWZ.
func (lhs Vec4[T]) SwizzleYXWZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYXWW returns a new vector with the components of this
// vector in the order of YXWW.
func (lhs Vec4[T]) SwizzleYXWW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYYXX returns a new vector with the components of this
// vector in the order of YYXX.
func (lhs Vec4[T]) SwizzleYYXX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYYXY returns a new vector with the components of this
// vector in the order of YYXY.
func (lhs Vec4[T]) SwizzleYYXY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYYXZ returns a new vector with the components of this
// vector in the order of YYXZ.
func (lhs Vec4[T]) SwizzleYYXZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYXW returns a new vector with the components of this
// vector in the order of YYXW.
func (lhs Vec4[T]) SwizzleYYXW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYYYX returns a new vector with the components of this
// vector in the order of YYYX.
func (lhs Vec4[T]) SwizzleYYYX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYYY returns a new vector with the components of this
// vector in the order of YYYY.
func (lhs Vec4[T]) SwizzleYYYY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYYZ returns a new vector with the components of this
// vector in the order of YYYZ.
func (lhs Vec4[T]) SwizzleYYYZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYYYW returns a new vector with the components of this
// vector in the order of YYYW.
func (lhs Vec4[T]) SwizzleYYYW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYYZX returns a new vector with the components of this
// vector in the order of YYZX.
func (lhs Vec4[T]) SwizzleYYZX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYYZY returns a new vector with the components of this
// vector in the order of YYZY.
func (lhs Vec4[T]) SwizzleYYZY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYYZZ returns a new vector with the components of this
// vector in the order of YYZZ.
func (lhs Vec4[T]) SwizzleYYZZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYYZW returns a new vector with the components of this
// vector in the order of YYZW.
func (lhs Vec4[T]) SwizzleYYZW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYYWX returns a new vector with the components of this
// vector in the order of YYWX.
func (lhs Vec4[T]) SwizzleYYWX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYYWY returns a new vector with the components of this
// vector in the order of YYWY.
func (lhs Vec4[T]) SwizzleYYWY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYYWZ returns a new vector with the components of this
// vector in the order of YYWZ.
func (lhs Vec4[T]) SwizzleYYWZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYYWW returns a new vector with the components of this
// vector in the order of YYWW.
func (lhs Vec4[T]) SwizzleYYWW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYZXX returns a new vector with the components of this
// vector in the order of YZXX.
func (lhs Vec4[T]) SwizzleYZXX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYZXY returns a new vector with the components of this
// vector in the order of YZXY.
func (lhs Vec4[T]) SwizzleYZXY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYZXZ returns a new vector with the components of this
// vector in the order of YZXZ.
func (lhs Vec4[T]) SwizzleYZXZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYZXW returns a new vector with the components of this
// vector in the order of YZXW.
func (lhs Vec4[T]) SwizzleYZXW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYZYX returns a new vector with the components of this
// vector in the order of YZYX.
func (lhs Vec4[T]) SwizzleYZYX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYZYY returns a new vector with the components of this
// vector in the order of YZYY.
func (lhs Vec4[T]) SwizzleYZYY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZYZ returns a new vector with the components of this
// vector in the order of YZYZ.
func (lhs Vec4[T]) SwizzleYZYZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZYW returns a new vector with the components of this
// vector in the order of YZYW.
func (lhs Vec4[T]) SwizzleYZYW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYZZX returns a new vector with the components of this
// vector in the order of YZZX.
func (lhs Vec4[T]) SwizzleYZZX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZZY returns a new vector with the components of this
// vector in the order of YZZY.
func (lhs Vec4[T]) SwizzleYZZY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZZ returns a new vector with the components of this
// vector in the order of YZZZ.
func (lhs Vec4[T]) SwizzleYZZZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYZZW returns a new vector with the components of this
// vector in the order of YZZW.
func (lhs Vec4[T]) SwizzleYZZW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYZWX returns a new vector with the components of this
// vector in the order of YZWX.
func (lhs Vec4[T]) SwizzleYZWX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYZWY returns a new vector with the components of this
// vector in the order of YZWY.
func (lhs Vec4[T]) SwizzleYZWY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYZWZ returns a new vector with the components of this
// vector in the order of YZWZ.
func (lhs Vec4[T]) SwizzleYZWZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYZWW returns a new vector with the components of this
// vector in the order of YZWW.
func (lhs Vec4[T]) SwizzleYZWW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleYWXX returns a new vector with the components of this
// vector in the order of YWXX.
func (lhs Vec4[T]) SwizzleYWXX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYWXY returns a new vector with the components of this
// vector in the order of YWXY.
func (lhs Vec4[T]) SwizzleYWXY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYWXZ returns a new vector with the components of this
// vector in the order of YWXZ.
func (lhs Vec4[T]) SwizzleYWXZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYWXW returns a new vector with the components of this
// vector in the order of YWXW.
func (lhs Vec4[T]) SwizzleYWXW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleYWYX returns a new vector with the components of this
// vector in the order of YWYX.
func (lhs Vec4[T]) SwizzleYWYX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYWYY returns a new vector with the components of this
// vector in the order of YWYY.
func (lhs Vec4[T]) SwizzleYWYY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYWYZ returns a new vector with the components of this
// vector in the order of YWYZ.
func (lhs Vec4[T]) SwizzleYWYZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYWYW returns a new vector with the components of this
// vector in the order of YWYW.
func (lhs Vec4[T]) SwizzleYWYW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleYWZX returns a new vector with the components of this
// vector in the order of YWZX.
func (lhs Vec4[T]) SwizzleYWZX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYWZY returns a new vector with the components of this
// vector in the order of YWZY.
func (lhs Vec4[T]) SwizzleYWZY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYWZZ returns a new vector with the components of this
// vector in the order of YWZZ.
func (lhs Vec4[T]) SwizzleYWZZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYWZW returns a new vector with the components of this
// vector in the order of YWZW.
func (lhs Vec4[T]) SwizzleYWZW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleYWWX returns a new vector with the components of this
// vector in the order of YWWX.
func (lhs Vec4[T]) SwizzleYWWX() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleYWWY returns a new vector with the components of this
// vector in the order of YWWY.
func (lhs Vec4[T]) SwizzleYWWY() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleYWWZ returns a new vector with the components of this
// vector in the order of YWWZ.
func (lhs Vec4[T]) SwizzleYWWZ() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleYWWW returns a new vector with the components of this
// vector in the order of YWWW.
func (lhs Vec4[T]) SwizzleYWWW() Vec4[T] {
	return Vec4[T]{
		lhs[1],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZXXX returns a new vector with the components of this
// vector in the order of ZXXX.
func (lhs Vec4[T]) SwizzleZXXX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXXY returns a new vector with the components of this
// vector in the order of ZXXY.
func (lhs Vec4[T]) SwizzleZXXY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXXZ returns a new vector with the components of this
// vector in the order of ZXXZ.
func (lhs Vec4[T]) SwizzleZXXZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZXXW returns a new vector with the components of this
// vector in the order of ZXXW.
func (lhs Vec4[T]) SwizzleZXXW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZXYX returns a new vector with the components of this
// vector in the order of ZXYX.
func (lhs Vec4[T]) SwizzleZXYX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZXYY returns a new vector with the components of this
// vector in the order of ZXYY.
func (lhs Vec4[T]) SwizzleZXYY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZXYZ returns a new vector with the components of this
// vector in the order of ZXYZ.
func (lhs Vec4[T]) SwizzleZXYZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZXYW returns a new vector with the components of this
// vector in the order of ZXYW.
func (lhs Vec4[T]) SwizzleZXYW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZXZX returns a new vector with the components of this
// vector in the order of ZXZX.
func (lhs Vec4[T]) SwizzleZXZX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZXZY returns a new vector with the components of this
// vector in the order of ZXZY.
func (lhs Vec4[T]) SwizzleZXZY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZXZZ returns a new vector with the components of this
// vector in the order of ZXZZ.
func (lhs Vec4[T]) SwizzleZXZZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXZW returns a new vector with the components of this
// vector in the order of ZXZW.
func (lhs Vec4[T]) SwizzleZXZW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZXWX returns a new vector with the components of this
// vector in the order of ZXWX.
func (lhs Vec4[T]) SwizzleZXWX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZXWY returns a new vector with the components of this
// vector in the order of ZXWY.
func (lhs Vec4[T]) SwizzleZXWY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZXWZ returns a new vector with the components of this
// vector in the order of ZXWZ.
func (lhs Vec4[T]) SwizzleZXWZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZXWW returns a new vector with the components of this
// vector in the order of ZXWW.
func (lhs Vec4[T]) SwizzleZXWW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZYXX returns a new vector with the components of this
// vector in the order of ZYXX.
func (lhs Vec4[T]) SwizzleZYXX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZYXY returns a new vector with the components of this
// vector in the order of ZYXY.
func (lhs Vec4[T]) SwizzleZYXY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZYXZ returns a new vector with the components of this
// vector in the order of ZYXZ.
func (lhs Vec4[T]) SwizzleZYXZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYXW returns a new vector with the components of this
// vector in the order of ZYXW.
func (lhs Vec4[T]) SwizzleZYXW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZYYX returns a new vector with the components of this
// vector in the order of ZYYX.
func (lhs Vec4[T]) SwizzleZYYX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYYY returns a new vector with the components of this
// vector in the order of ZYYY.
func (lhs Vec4[T]) SwizzleZYYY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYYZ returns a new vector with the components of this
// vector in the order of ZYYZ.
func (lhs Vec4[T]) SwizzleZYYZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZYYW returns a new vector with the components of this
// vector in the order of ZYYW.
func (lhs Vec4[T]) SwizzleZYYW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZYZX returns a new vector with the components of this
// vector in the order of ZYZX.
func (lhs Vec4[T]) SwizzleZYZX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZYZY returns a new vector with the components of this
// vector in the order of ZYZY.
func (lhs Vec4[T]) SwizzleZYZY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZYZZ returns a new vector with the components of this
// vector in the order of ZYZZ.
func (lhs Vec4[T]) SwizzleZYZZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZYZW returns a new vector with the components of this
// vector in the order of ZYZW.
func (lhs Vec4[T]) SwizzleZYZW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZYWX returns a new vector with the components of this
// vector in the order of ZYWX.
func (lhs Vec4[T]) SwizzleZYWX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZYWY returns a new vector with the components of this
// vector in the order of ZYWY.
func (lhs Vec4[T]) SwizzleZYWY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZYWZ returns a new vector with the components of this
// vector in the order of ZYWZ.
func (lhs Vec4[T]) SwizzleZYWZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZYWW returns a new vector with the components of this
// vector in the order of ZYWW.
func (lhs Vec4[T]) SwizzleZYWW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZZXX returns a new vector with the components of this
// vector in the order of ZZXX.
func (lhs Vec4[T]) SwizzleZZXX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZZXY returns a new vector with the components of this
// vector in the order of ZZXY.
func (lhs Vec4[T]) SwizzleZZXY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZZXZ returns a new vector with the components of this
// vector in the order of ZZXZ.
func (lhs Vec4[T]) SwizzleZZXZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZZXW returns a new vector with the components of this
// vector in the order of ZZXW.
func (lhs Vec4[T]) SwizzleZZXW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZZYX returns a new vector with the components of this
// vector in the order of ZZYX.
func (lhs Vec4[T]) SwizzleZZYX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZZYY returns a new vector with the components of this
// vector in the order of ZZYY.
func (lhs Vec4[T]) SwizzleZZYY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZZYZ returns a new vector with the components of this
// vector in the order of ZZYZ.
func (lhs Vec4[T]) SwizzleZZYZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZYW returns a new vector with the components of this
// vector in the order of ZZYW.
func (lhs Vec4[T]) SwizzleZZYW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZZZX returns a new vector with the components of this
// vector in the order of ZZZX.
func (lhs Vec4[T]) SwizzleZZZX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZZY returns a new vector with the components of this
// vector in the order of ZZZY.
func (lhs Vec4[T]) SwizzleZZZY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZZ returns a new vector with the components of this
// vector in the order of ZZZZ.
func (lhs Vec4[T]) SwizzleZZZZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZZZW returns a new vector with the components of this
// vector in the order of ZZZW.
func (lhs Vec4[T]) SwizzleZZZW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZZWX returns a new vector with the components of this
// vector in the order of ZZWX.
func (lhs Vec4[T]) SwizzleZZWX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZZWY returns a new vector with the components of this
// vector in the order of ZZWY.
func (lhs Vec4[T]) SwizzleZZWY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZZWZ returns a new vector with the components of this
// vector in the order of ZZWZ.
func (lhs Vec4[T]) SwizzleZZWZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZZWW returns a new vector with the components of this
// vector in the order of ZZWW.
func (lhs Vec4[T]) SwizzleZZWW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleZWXX returns a new vector with the components of this
// vector in the order of ZWXX.
func (lhs Vec4[T]) SwizzleZWXX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZWXY returns a new vector with the components of this
// vector in the order of ZWXY.
func (lhs Vec4[T]) SwizzleZWXY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZWXZ returns a new vector with the components of this
// vector in the order of ZWXZ.
func (lhs Vec4[T]) SwizzleZWXZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZWXW returns a new vector with the components of this
// vector in the order of ZWXW.
func (lhs Vec4[T]) SwizzleZWXW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleZWYX returns a new vector with the components of this
// vector in the order of ZWYX.
func (lhs Vec4[T]) SwizzleZWYX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZWYY returns a new vector with the components of this
// vector in the order of ZWYY.
func (lhs Vec4[T]) SwizzleZWYY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZWYZ returns a new vector with the components of this
// vector in the order of ZWYZ.
func (lhs Vec4[T]) SwizzleZWYZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZWYW returns a new vector with the components of this
// vector in the order of ZWYW.
func (lhs Vec4[T]) SwizzleZWYW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleZWZX returns a new vector with the components of this
// vector in the order of ZWZX.
func (lhs Vec4[T]) SwizzleZWZX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZWZY returns a new vector with the components of this
// vector in the order of ZWZY.
func (lhs Vec4[T]) SwizzleZWZY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZWZZ returns a new vector with the components of this
// vector in the order of ZWZZ.
func (lhs Vec4[T]) SwizzleZWZZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZWZW returns a new vector with the components of this
// vector in the order of ZWZW.
func (lhs Vec4[T]) SwizzleZWZW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleZWWX returns a new vector with the components of this
// vector in the order of ZWWX.
func (lhs Vec4[T]) SwizzleZWWX() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleZWWY returns a new vector with the components of this
// vector in the order of ZWWY.
func (lhs Vec4[T]) SwizzleZWWY() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleZWWZ returns a new vector with the components of this
// vector in the order of ZWWZ.
func (lhs Vec4[T]) SwizzleZWWZ() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleZWWW returns a new vector with the components of this
// vector in the order of ZWWW.
func (lhs Vec4[T]) SwizzleZWWW() Vec4[T] {
	return Vec4[T]{
		lhs[2],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWXXX returns a new vector with the components of this
// vector in the order of WXXX.
func (lhs Vec4[T]) SwizzleWXXX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWXXY returns a new vector with the components of this
// vector in the order of WXXY.
func (lhs Vec4[T]) SwizzleWXXY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWXXZ returns a new vector with the components of this
// vector in the order of WXXZ.
func (lhs Vec4[T]) SwizzleWXXZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWXXW returns a new vector with the components of this
// vector in the order of WXXW.
func (lhs Vec4[T]) SwizzleWXXW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWXYX returns a new vector with the components of this
// vector in the order of WXYX.
func (lhs Vec4[T]) SwizzleWXYX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWXYY returns a new vector with the components of this
// vector in the order of WXYY.
func (lhs Vec4[T]) SwizzleWXYY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWXYZ returns a new vector with the components of this
// vector in the order of WXYZ.
func (lhs Vec4[T]) SwizzleWXYZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWXYW returns a new vector with the components of this
// vector in the order of WXYW.
func (lhs Vec4[T]) SwizzleWXYW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWXZX returns a new vector with the components of this
// vector in the order of WXZX.
func (lhs Vec4[T]) SwizzleWXZX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWXZY returns a new vector with the components of this
// vector in the order of WXZY.
func (lhs Vec4[T]) SwizzleWXZY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWXZZ returns a new vector with the components of this
// vector in the order of WXZZ.
func (lhs Vec4[T]) SwizzleWXZZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWXZW returns a new vector with the components of this
// vector in the order of WXZW.
func (lhs Vec4[T]) SwizzleWXZW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWXWX returns a new vector with the components of this
// vector in the order of WXWX.
func (lhs Vec4[T]) SwizzleWXWX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWXWY returns a new vector with the components of this
// vector in the order of WXWY.
func (lhs Vec4[T]) SwizzleWXWY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWXWZ returns a new vector with the components of this
// vector in the order of WXWZ.
func (lhs Vec4[T]) SwizzleWXWZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWXWW returns a new vector with the components of this
// vector in the order of WXWW.
func (lhs Vec4[T]) SwizzleWXWW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[0],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWYXX returns a new vector with the components of this
// vector in the order of WYXX.
func (lhs Vec4[T]) SwizzleWYXX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWYXY returns a new vector with the components of this
// vector in the order of WYXY.
func (lhs Vec4[T]) SwizzleWYXY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWYXZ returns a new vector with the components of this
// vector in the order of WYXZ.
func (lhs Vec4[T]) SwizzleWYXZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWYXW returns a new vector with the components of this
// vector in the order of WYXW.
func (lhs Vec4[T]) SwizzleWYXW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWYYX returns a new vector with the components of this
// vector in the order of WYYX.
func (lhs Vec4[T]) SwizzleWYYX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWYYY returns a new vector with the components of this
// vector in the order of WYYY.
func (lhs Vec4[T]) SwizzleWYYY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWYYZ returns a new vector with the components of this
// vector in the order of WYYZ.
func (lhs Vec4[T]) SwizzleWYYZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWYYW returns a new vector with the components of this
// vector in the order of WYYW.
func (lhs Vec4[T]) SwizzleWYYW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWYZX returns a new vector with the components of this
// vector in the order of WYZX.
func (lhs Vec4[T]) SwizzleWYZX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWYZY returns a new vector with the components of this
// vector in the order of WYZY.
func (lhs Vec4[T]) SwizzleWYZY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWYZZ returns a new vector with the components of this
// vector in the order of WYZZ.
func (lhs Vec4[T]) SwizzleWYZZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWYZW returns a new vector with the components of this
// vector in the order of WYZW.
func (lhs Vec4[T]) SwizzleWYZW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWYWX returns a new vector with the components of this
// vector in the order of WYWX.
func (lhs Vec4[T]) SwizzleWYWX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWYWY returns a new vector with the components of this
// vector in the order of WYWY.
func (lhs Vec4[T]) SwizzleWYWY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWYWZ returns a new vector with the components of this
// vector in the order of WYWZ.
func (lhs Vec4[T]) SwizzleWYWZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWYWW returns a new vector with the components of this
// vector in the order of WYWW.
func (lhs Vec4[T]) SwizzleWYWW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[1],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWZXX returns a new vector with the components of this
// vector in the order of WZXX.
func (lhs Vec4[T]) SwizzleWZXX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWZXY returns a new vector with the components of this
// vector in the order of WZXY.
func (lhs Vec4[T]) SwizzleWZXY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWZXZ returns a new vector with the components of this
// vector in the order of WZXZ.
func (lhs Vec4[T]) SwizzleWZXZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWZXW returns a new vector with the components of this
// vector in the order of WZXW.
func (lhs Vec4[T]) SwizzleWZXW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWZYX returns a new vector with the components of this
// vector in the order of WZYX.
func (lhs Vec4[T]) SwizzleWZYX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWZYY returns a new vector with the components of this
// vector in the order of WZYY.
func (lhs Vec4[T]) SwizzleWZYY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWZYZ returns a new vector with the components of this
// vector in the order of WZYZ.
func (lhs Vec4[T]) SwizzleWZYZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWZYW returns a new vector with the components of this
// vector in the order of WZYW.
func (lhs Vec4[T]) SwizzleWZYW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWZZX returns a new vector with the components of this
// vector in the order of WZZX.
func (lhs Vec4[T]) SwizzleWZZX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWZZY returns a new vector with the components of this
// vector in the order of WZZY.
func (lhs Vec4[T]) SwizzleWZZY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWZZZ returns a new vector with the components of this
// vector in the order of WZZZ.
func (lhs Vec4[T]) SwizzleWZZZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWZZW returns a new vector with the components of this
// vector in the order of WZZW.
func (lhs Vec4[T]) SwizzleWZZW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWZWX returns a new vector with the components of this
// vector in the order of WZWX.
func (lhs Vec4[T]) SwizzleWZWX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWZWY returns a new vector with the components of this
// vector in the order of WZWY.
func (lhs Vec4[T]) SwizzleWZWY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWZWZ returns a new vector with the components of this
// vector in the order of WZWZ.
func (lhs Vec4[T]) SwizzleWZWZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWZWW returns a new vector with the components of this
// vector in the order of WZWW.
func (lhs Vec4[T]) SwizzleWZWW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[2],
		lhs[3],
		lhs[3],
	}
}

// SwizzleWWXX returns a new vector with the components of this
// vector in the order of WWXX.
func (lhs Vec4[T]) SwizzleWWXX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[0],
	}
}

// SwizzleWWXY returns a new vector with the components of this
// vector in the order of WWXY.
func (lhs Vec4[T]) SwizzleWWXY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[1],
	}
}

// SwizzleWWXZ returns a new vector with the components of this
// vector in the order of WWXZ.
func (lhs Vec4[T]) SwizzleWWXZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[2],
	}
}

// SwizzleWWXW returns a new vector with the components of this
// vector in the order of WWXW.
func (lhs Vec4[T]) SwizzleWWXW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[0],
		lhs[3],
	}
}

// SwizzleWWYX returns a new vector with the components of this
// vector in the order of WWYX.
func (lhs Vec4[T]) SwizzleWWYX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[0],
	}
}

// SwizzleWWYY returns a new vector with the components of this
// vector in the order of WWYY.
func (lhs Vec4[T]) SwizzleWWYY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[1],
	}
}

// SwizzleWWYZ returns a new vector with the components of this
// vector in the order of WWYZ.
func (lhs Vec4[T]) SwizzleWWYZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[2],
	}
}

// SwizzleWWYW returns a new vector with the components of this
// vector in the order of WWYW.
func (lhs Vec4[T]) SwizzleWWYW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[1],
		lhs[3],
	}
}

// SwizzleWWZX returns a new vector with the components of this
// vector in the order of WWZX.
func (lhs Vec4[T]) SwizzleWWZX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[0],
	}
}

// SwizzleWWZY returns a new vector with the components of this
// vector in the order of WWZY.
func (lhs Vec4[T]) SwizzleWWZY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[1],
	}
}

// SwizzleWWZZ returns a new vector with the components of this
// vector in the order of WWZZ.
func (lhs Vec4[T]) SwizzleWWZZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[2],
	}
}

// SwizzleWWZW returns a new vector with the components of this
// vector in the order of WWZW.
func (lhs Vec4[T]) SwizzleWWZW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[2],
		lhs[3],
	}
}

// SwizzleWWWX returns a new vector with the components of this
// vector in the order of WWWX.
func (lhs Vec4[T]) SwizzleWWWX() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[0],
	}
}

// SwizzleWWWY returns a new vector with the components of this
// vector in the order of WWWY.
func (lhs Vec4[T]) SwizzleWWWY() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[1],
	}
}

// SwizzleWWWZ returns a new vector with the components of this
// vector in the order of WWWZ.
func (lhs Vec4[T]) SwizzleWWWZ() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[2],
	}
}

// SwizzleWWWW returns a new vector with the components of this
// vector in the order of WWWW.
func (lhs Vec4[T]) SwizzleWWWW() Vec4[T] {
	return Vec4[T]{
		lhs[3],
		lhs[3],
		lhs[3],
		lhs[3],
	}
}

func (lhs Vec4[T]) XY() (x, y T) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec4[T]) XYZ() (x, y, z T) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec4[T]) XYZW() (x, y, z, w T) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	w = lhs[3]
	return
}

func (lhs Vec4[T]) ToVec4f() Vec4f {
	return Vec4f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4[T]) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
		float32(lhs[3]),
	}
}

func (lhs Vec4[T]) String() string {
	return fmt.Sprintf(
		"vec4(%v, %v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
		lhs[3],
	)
}
