// Code generated by generate.go: DO NOT EDIT.

package glm

import "fmt"
import "math"

// Vec3f is an alias for the float32 variant of Vec3
type Vec3f = Vec3[float32]

// Vec3u is an alias for the uint32 variant of Vec3
type Vec3u = Vec3[uint32]

// Vec3uh is an alias for the uint16 variant of Vec3
type Vec3uh = Vec3[uint16]

// Vec3 is a vector of dimension 3.
type Vec3[T Numeric] [3]T

func (lhs Vec3[T]) Dot(rhs Vec3[T]) T {
	return lhs[0]*rhs[0] + lhs[1]*rhs[1] + lhs[2]*rhs[2]
}

func (lhs Vec3[T]) LengthSqr() T {
	return lhs.Dot(lhs)
}

func (lhs Vec3[T]) Length() T {
	return T(math.Sqrt(float64(lhs.Dot(lhs))))
}

func (lhs Vec3[T]) Normalize() Vec3[T] {
	return lhs.Scale(1.0 / lhs.Length())
}

func (lhs Vec3[T]) Scale(s T) Vec3[T] {
	return Vec3[T]{
		lhs[0] * s,
		lhs[1] * s,
		lhs[2] * s,
	}
}

func (lhs Vec3[T]) Reciprocal() Vec3[T] {
	return Vec3[T]{
		1.0 / lhs[0],
		1.0 / lhs[1],
		1.0 / lhs[2],
	}
}

func (lhs Vec3[T]) Add(rhs Vec3[T]) Vec3[T] {
	return Vec3[T]{
		lhs[0] + rhs[0],
		lhs[1] + rhs[1],
		lhs[2] + rhs[2],
	}
}

func (lhs Vec3[T]) Sub(rhs Vec3[T]) Vec3[T] {
	return Vec3[T]{
		lhs[0] - rhs[0],
		lhs[1] - rhs[1],
		lhs[2] - rhs[2],
	}
}

func (lhs Vec3[T]) Mul(rhs Vec3[T]) Vec3[T] {
	return Vec3[T]{
		lhs[0] * rhs[0],
		lhs[1] * rhs[1],
		lhs[2] * rhs[2],
	}
}

func (lhs Vec3[T]) Div(rhs Vec3[T]) Vec3[T] {
	return Vec3[T]{
		lhs[0] / rhs[0],
		lhs[1] / rhs[1],
		lhs[2] / rhs[2],
	}
}

func (lhs Vec3[T]) Min(rhs Vec3[T]) Vec3[T] {
	return Vec3[T]{
		min(lhs[0], rhs[0]),
		min(lhs[1], rhs[1]),
		min(lhs[2], rhs[2]),
	}
}

func (lhs Vec3[T]) Max(rhs Vec3[T]) Vec3[T] {
	return Vec3[T]{
		max(lhs[0], rhs[0]),
		max(lhs[1], rhs[1]),
		max(lhs[2], rhs[2]),
	}
}

func (lhs Vec3[T]) Extend(w T) Vec4[T] {
	return Vec4[T]{
		lhs[0],
		lhs[1],
		lhs[2],
		w,
	}
}

func (lhs Vec3[T]) Truncate() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXX returns a new vector with the components of this
// vector in the order of XX.
func (lhs Vec3[T]) SwizzleXX() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[0],
	}
}

// SwizzleXY returns a new vector with the components of this
// vector in the order of XY.
func (lhs Vec3[T]) SwizzleXY() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[1],
	}
}

// SwizzleXZ returns a new vector with the components of this
// vector in the order of XZ.
func (lhs Vec3[T]) SwizzleXZ() Vec2[T] {
	return Vec2[T]{
		lhs[0],
		lhs[2],
	}
}

// SwizzleYX returns a new vector with the components of this
// vector in the order of YX.
func (lhs Vec3[T]) SwizzleYX() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[0],
	}
}

// SwizzleYY returns a new vector with the components of this
// vector in the order of YY.
func (lhs Vec3[T]) SwizzleYY() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[1],
	}
}

// SwizzleYZ returns a new vector with the components of this
// vector in the order of YZ.
func (lhs Vec3[T]) SwizzleYZ() Vec2[T] {
	return Vec2[T]{
		lhs[1],
		lhs[2],
	}
}

// SwizzleZX returns a new vector with the components of this
// vector in the order of ZX.
func (lhs Vec3[T]) SwizzleZX() Vec2[T] {
	return Vec2[T]{
		lhs[2],
		lhs[0],
	}
}

// SwizzleZY returns a new vector with the components of this
// vector in the order of ZY.
func (lhs Vec3[T]) SwizzleZY() Vec2[T] {
	return Vec2[T]{
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZ returns a new vector with the components of this
// vector in the order of ZZ.
func (lhs Vec3[T]) SwizzleZZ() Vec2[T] {
	return Vec2[T]{
		lhs[2],
		lhs[2],
	}
}

// SwizzleXXX returns a new vector with the components of this
// vector in the order of XXX.
func (lhs Vec3[T]) SwizzleXXX() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[0],
		lhs[0],
	}
}

// SwizzleXXY returns a new vector with the components of this
// vector in the order of XXY.
func (lhs Vec3[T]) SwizzleXXY() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[0],
		lhs[1],
	}
}

// SwizzleXXZ returns a new vector with the components of this
// vector in the order of XXZ.
func (lhs Vec3[T]) SwizzleXXZ() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[0],
		lhs[2],
	}
}

// SwizzleXYX returns a new vector with the components of this
// vector in the order of XYX.
func (lhs Vec3[T]) SwizzleXYX() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[0],
	}
}

// SwizzleXYY returns a new vector with the components of this
// vector in the order of XYY.
func (lhs Vec3[T]) SwizzleXYY() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[1],
	}
}

// SwizzleXYZ returns a new vector with the components of this
// vector in the order of XYZ.
func (lhs Vec3[T]) SwizzleXYZ() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[1],
		lhs[2],
	}
}

// SwizzleXZX returns a new vector with the components of this
// vector in the order of XZX.
func (lhs Vec3[T]) SwizzleXZX() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[2],
		lhs[0],
	}
}

// SwizzleXZY returns a new vector with the components of this
// vector in the order of XZY.
func (lhs Vec3[T]) SwizzleXZY() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[2],
		lhs[1],
	}
}

// SwizzleXZZ returns a new vector with the components of this
// vector in the order of XZZ.
func (lhs Vec3[T]) SwizzleXZZ() Vec3[T] {
	return Vec3[T]{
		lhs[0],
		lhs[2],
		lhs[2],
	}
}

// SwizzleYXX returns a new vector with the components of this
// vector in the order of YXX.
func (lhs Vec3[T]) SwizzleYXX() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[0],
		lhs[0],
	}
}

// SwizzleYXY returns a new vector with the components of this
// vector in the order of YXY.
func (lhs Vec3[T]) SwizzleYXY() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[0],
		lhs[1],
	}
}

// SwizzleYXZ returns a new vector with the components of this
// vector in the order of YXZ.
func (lhs Vec3[T]) SwizzleYXZ() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[0],
		lhs[2],
	}
}

// SwizzleYYX returns a new vector with the components of this
// vector in the order of YYX.
func (lhs Vec3[T]) SwizzleYYX() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[1],
		lhs[0],
	}
}

// SwizzleYYY returns a new vector with the components of this
// vector in the order of YYY.
func (lhs Vec3[T]) SwizzleYYY() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[1],
		lhs[1],
	}
}

// SwizzleYYZ returns a new vector with the components of this
// vector in the order of YYZ.
func (lhs Vec3[T]) SwizzleYYZ() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[1],
		lhs[2],
	}
}

// SwizzleYZX returns a new vector with the components of this
// vector in the order of YZX.
func (lhs Vec3[T]) SwizzleYZX() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[2],
		lhs[0],
	}
}

// SwizzleYZY returns a new vector with the components of this
// vector in the order of YZY.
func (lhs Vec3[T]) SwizzleYZY() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[2],
		lhs[1],
	}
}

// SwizzleYZZ returns a new vector with the components of this
// vector in the order of YZZ.
func (lhs Vec3[T]) SwizzleYZZ() Vec3[T] {
	return Vec3[T]{
		lhs[1],
		lhs[2],
		lhs[2],
	}
}

// SwizzleZXX returns a new vector with the components of this
// vector in the order of ZXX.
func (lhs Vec3[T]) SwizzleZXX() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[0],
		lhs[0],
	}
}

// SwizzleZXY returns a new vector with the components of this
// vector in the order of ZXY.
func (lhs Vec3[T]) SwizzleZXY() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[0],
		lhs[1],
	}
}

// SwizzleZXZ returns a new vector with the components of this
// vector in the order of ZXZ.
func (lhs Vec3[T]) SwizzleZXZ() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[0],
		lhs[2],
	}
}

// SwizzleZYX returns a new vector with the components of this
// vector in the order of ZYX.
func (lhs Vec3[T]) SwizzleZYX() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[1],
		lhs[0],
	}
}

// SwizzleZYY returns a new vector with the components of this
// vector in the order of ZYY.
func (lhs Vec3[T]) SwizzleZYY() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[1],
		lhs[1],
	}
}

// SwizzleZYZ returns a new vector with the components of this
// vector in the order of ZYZ.
func (lhs Vec3[T]) SwizzleZYZ() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[1],
		lhs[2],
	}
}

// SwizzleZZX returns a new vector with the components of this
// vector in the order of ZZX.
func (lhs Vec3[T]) SwizzleZZX() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[2],
		lhs[0],
	}
}

// SwizzleZZY returns a new vector with the components of this
// vector in the order of ZZY.
func (lhs Vec3[T]) SwizzleZZY() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[2],
		lhs[1],
	}
}

// SwizzleZZZ returns a new vector with the components of this
// vector in the order of ZZZ.
func (lhs Vec3[T]) SwizzleZZZ() Vec3[T] {
	return Vec3[T]{
		lhs[2],
		lhs[2],
		lhs[2],
	}
}

func (lhs Vec3[T]) XY() (x, y T) {
	x = lhs[0]
	y = lhs[1]
	return
}

func (lhs Vec3[T]) XYZ() (x, y, z T) {
	x = lhs[0]
	y = lhs[1]
	z = lhs[2]
	return
}

func (lhs Vec3[T]) ToVec3f() Vec3f {
	return Vec3f{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3[T]) ToWGPU() [4]float32 {
	return [4]float32{
		float32(lhs[0]),
		float32(lhs[1]),
		float32(lhs[2]),
	}
}

func (lhs Vec3[T]) String() string {
	return fmt.Sprintf(
		"vec3(%v, %v, %v)",
		lhs[0],
		lhs[1],
		lhs[2],
	)
}
